name: CD

on:
  push:
    tags: 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: "ghcr.io/geode-solutions/centos:master"
    strategy:
      matrix:
        config:
        - {python: "3.8", tag: "cp38-cp38"}
        - {python: "3.9", tag: "cp39-cp39"}
        - {python: "3.10", tag: "cp310-cp310"}

    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-linux-${{ matrix.config.python }}-${{ hashFiles('package-lock.json') }}
    - name: Generate package
      id: package
      run: |
        export PATH=/opt/python/${{ matrix.config.tag }}/bin:$PATH
        npm config set cmake_PYTHON_VERSION ${{ matrix.config.python }}
        version="${GITHUB_REF##*/*/v}"
        echo ::set-output name=version::$version-python${{ matrix.config.python }}
        npm install
        npm run package -- $version-python${{ matrix.config.python }} linux 
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: "opengeode-io-${{ steps.package.outputs.version }}-linux.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}    

  
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
        - {python: "3.8", tag: "cp38-cp38"}
        - {python: "3.9", tag: "cp39-cp39"}
        - {python: "3.10", tag: "cp310-cp310"}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.config.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-win64-${{ matrix.config.python }}-${{ hashFiles('package-lock.json') }}
    - name: Generate package
      id: package
      run: |
        npm config set cmake_PYTHON_VERSION ${{ matrix.config.python }}
        $version = ${env:GITHUB_REF} -replace 'refs\/tags\/v', ''
        echo "::set-output name=version::$version-python${{ matrix.config.python }}"
        npm install
        npm run package -- $version-python${{ matrix.config.python }} win64 
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: "opengeode-io-${{ steps.package.outputs.version }}-win64.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        